### ISSUE TITLE
Speed Dreams is missing on Flathub.org

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.speed_dreams.SpeedDreams#1]
It seems that Speed Dreams is missing on Flathub.org. It's showing in GNOME Software, but there is `(null)` instead of the `<ul>` list.

This is most likely a problem with AppStream metadata. Here is an output of the `appstream-util validate` command:
```
org.speed_dreams.SpeedDreams.appdata.xml: FAILED:
• tag-missing           : <translation> not specified
• style-invalid         : <p> requires sentence case [(null)]
• style-invalid         : <p> does not end in '.|:|!' [(null)]
• style-invalid         : <p> is too short [(null)]
Validation of files failed
```

**Comment by TingPing** [comment]
https://github.com/flathub/org.speed_dreams.SpeedDreams/commit/20355469e4604329af159ee99bce2f84145cc5cb

**Comment by AsciiWolf** [comment]
It seems that Speed Dreams is still missing on the Flathub website.

**Comment by son-link** [comment]
Edit and validate the appdata.xml
I hope this fixed the problem to view on the web

**Comment by AsciiWolf** [comment]
@son-link Seems to be still missing. :-(

**Comment by AsciiWolf** [comment]
Seems to be fixed now!
